---
aliases_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.aliases"

aliases: {
    'su': 'sudo su',
    'apt': 'sudo apt',
    'dpkg': 'sudo dpkg',
    'ls': 'ls --color=auto',
    'gnome-shell-restart': 'killall -3 gnome-shell',
}
