---
aliases_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.aliases"

aliases: {
    'su': 'sudo su',
    'apt': 'sudo apt',
    'dpkg': 'sudo dpkg',
    'ls': 'ls --color=auto',
    'gnome-shell-restart': 'killall -3 gnome-shell',
    'date': 'date "+%a %d %b %Y %I:%M:%S %p %Z"',
    'rustfmt': 'rustup run nightly rustfmt',
}
