---
- name: Enabling Blu-ray compatibility
  hosts: localhost
  connection: local
  vars_files:
    - ../debug_mode.yml
  vars:
    - makemkv_pkgs:
      - makemkv-bin
      - makemkv-oss

  tasks:
  - name: Adding MakeMKV PPA
    check_mode: '{{ debug_mode }}'
    ansible.builtin.apt_repository:
      repo: ppa:heyarje/makemkv-beta
      state: present
      update_cache: true

  - name: Installing MakeMKV
    check_mode: '{{ debug_mode }}'
    ansible.builtin.apt:
      name: '{{ makemkv_pkgs }}'
      state: present
