---
- name: Installing GNOME extensions
  hosts: localhost
  connection: local
  vars_files:
    - ../debug_mode.yml

  tasks:
  - name: Cloning gnome-shell-extension-installer repo
    check_mode: '{{ debug_mode }}'
    ansible.builtin.git:
      clone: true
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/Documents/gnome-shell-extension-installer"
      repo: "git@github.com:brunelli/gnome-shell-extension-installer.git"

  - name: Ensuring local bin directory exists
    check_mode: '{{ debug_mode }}'
    ansible.builtin.file:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
      state: directory

  - name: Symlinking gnome-shell-extension-installer
    check_mode: '{{ debug_mode }}'
    ansible.builtin.file:
      src: "{{ lookup('ansible.builtin.env', 'HOME') }}/Documents/gnome-shell-extension-installer/gnome-shell-extension-installer"
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/gnome-shell-extension-installer"
      state: link

  - name: Installing extensions
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      # 4709 -> Another Window Session Manager
      # 3733 -> Tiling Assistant
      # NOTE: --restart-shell doesn't seem to do anything (still need to restart
      #       manually)
      # NOTE: Consider putting these into a vars_files file if more get added
      cmd: gnome-shell-extension-installer 4709 3733 --restart-shell
