---
- name: Installing GNOME extensions
  hosts: localhost
  connection: local
  vars_files:
    - ../debug_mode.yml
  vars:
    - repo_name: gnome-shell-extension-installer

  tasks:
  - name: Ensuring local src directory exists
    check_mode: '{{ debug_mode }}'
    ansible.builtin.file:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/src"
      state: directory

  - name: Cloning {{ repo_name }} repo
    check_mode: '{{ debug_mode }}'
    ansible.builtin.get_url:
      url: "https://github.com/brunelli/{{ repo_name }}/archive/refs/heads/master.zip"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/src/"

  - name: Ensuring local bin directory exists
    check_mode: '{{ debug_mode }}'
    ansible.builtin.file:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
      state: directory

  - name: Unzipping {{ repo_name }}
    check_mode: '{{ debug_mode }}'
    ansible.builtin.unarchive:
      src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/src/{{ repo_name }}-master.zip"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/src/"

  - name: Removing {{ repo_name }} zip file
    check_mode: '{{ debug_mode }}'
    ansible.builtin.file:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/src/{{ repo_name }}-master.zip"
      state: absent

  - name: Symlinking {{ repo_name }}
    check_mode: '{{ debug_mode }}'
    ansible.builtin.file:
      src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/src/{{ repo_name }}-master/{{ repo_name }}"
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/{{ repo_name }}"
      state: link

  - name: Installing extensions
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      # 4709 -> Another Window Session Manager
      # 3733 -> Tiling Assistant
      # NOTE: --restart-shell doesn't seem to do anything (still need to restart
      #       manually)
      # NOTE: Consider putting these into a vars_files file if more get added
      cmd: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/{{ repo_name }} 4709 3733 --restart-shell"
