---
aliases_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.aliases"

aliases: {
    'su': 'sudo su',
    'apt': 'sudo apt',
    'dpkg': 'sudo dpkg',
    'date': 'date "+%a %d %b %Y %I:%M:%S %p %Z"',
    'ls': 'ls --color=auto',
    'arp': 'sudo arp',
    'add-apt-repository': 'sudo add-apt-repository',
}
