---
aliases_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.aliases"

aliases: {
          'su': 'sudo su',
          'apt': 'sudo apt',
          'dpkg': 'sudo dpkg',
          'arp': 'sudo arp',
          'poweroff': 'sudo poweroff',
          'reboot': 'sudo reboot',
          'jflap': 'java -jar $HOME/.local/bin/JFLAP7.1.jar'
         }
         
aliases_redhat_distros: {
                         'update-grub': 'sudo grub2-mkconfig -o /boot/grub2/grub.cfg'
                        }
