---
aliases_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.aliases"

aliases: {
          'su': 'sudo su',
          'apt': 'sudo apt',
          'dpkg': 'sudo dpkg',
          'arp': 'sudo arp',
          'poweroff': 'sudo poweroff',
          'reboot': 'sudo reboot',
          'jflap': 'java -jar $HOME/.local/bin/JFLAP7.1.jar',
          'win64g++': 'x86_64-w64-mingw32-g++ --static',    # for 64-bit Windows
          'win64gcc': 'x86_64-w64-mingw32-gcc --static',    # for 64-bit Windows
          'win32g++': 'i686-w64-mingw32-g++ --static',      # for 32-bit Windows
          'win32gcc': 'i686-w64-mingw32-gcc --static',      # for 32-bit Windows
          'arnoldc': '$SHELL $HOME/.local/bin/ArnoldC/run_arnoldc.sh',
          'ocaml-top': 'ocaml-top &',
          'chroot-startup': '$SHELL ~/Documents/projects/chroot_jail/chroot_startup.sh',
          'mpiclang': 'OMPI_CC=clang mpicc',
          'mpiclang++': 'OMPI_CC=clang++ mpic++'
         }
         
aliases_redhat_distros: {
                         'update-grub': 'sudo grub2-mkconfig -o /boot/grub2/grub.cfg'
                        }
