---
- name: Configuring Git
  hosts: localhost
  connection: local
  vars:
    - git_config_options: {
                           'user.name': 'TheOGChips',
                           'user.email': 'swindell.christian.g@gmail.com',
                           'credential.helper': 'store',
                           'core.sshcommand': 'ssh -i ~/.ssh/github -F /dev/null'
                          }
  vars_files:
    - debug_mode.yml
  
  tasks:
  - name: 'GIT CONFIG: Installing Git'
    check_mode: '{{ debug_mode }}'
    become: yes
    ansible.builtin.apt:
      name: git
      state: latest

  - name: 'GIT CONFIG: Configuring global Git settings'
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      cmd: git config --global {{ item.key }} "{{ item.value }}"
    loop: "{{ git_config_options | dict2items }}"
