# run using ansible-playbook -K init.yml
---
# The general play
# echo "alias su='sudo su'" >> "$HOME"/.aliases

- name: Complete initial setup of localhost
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - pkgs_to_remove.yml
    - pkgs_to_install.yml
  #become_method: sudo
  #vars_files:
  #- vars/main.yml

  #roles:
  #- role: geerlingguy.apache

  tasks:
  - name: Remove unwanted KDE packages
    check_mode: on
    ansible.builtin.apt:
      name: "{{ pkgs_to_remove + pkgs_to_remove_from_debian }}"
      state: absent
      
  - name: Remove these packages manually
    block:
      - name: Attempting to remove packages
        ansible.builtin.shell:
          cmd: rm -r $(find / -name "{{ item }}")
          warn: false
        loop:
          - '*contactthemeeditor*'
          - '*contactprintthemeeditor*'
          - '*headerthemeeditor*'
          - '*pimdataexporter*'
          - '*sieveeditor*'
    rescue:
      - name: Files couldn't be found
        ansible.builtin.debug:
          msg: The files could not be found and have likely already been deleted'
      
      #ignore_errors: true
    #ansible.builtin.copy:
      #src: files/site/index.html
      #dest: /var/www/html/index.html
      #owner: root
      #group: root
      #mode: 0644
  - name: Upgrade current packages on machine
    ansible.builtin.apt:
      upgrade: safe
      
  - name: Install net-tools
    ansible.builtin.apt:
      name: net-tools
      state: latest
      
  - name: Make edits to /etc/sudoers
    become_user: chris
    ansible.builtin.command:
      cmd: konsole -e 'bash visudo_edits.sh apt dpkg $HOME/.aliases'
      
  - name: Removing GRUB menu timeout
    ansible.builtin.replace:
      path: /etc/default/grub
      regexp: 'GRUB_TIMEOUT=5'
      replace: 'GRUB_TIMEOUT=-1'
      
  - name: Updating GRUB
    ansible.builtin.command:
      cmd: update-grub
    # echo "alias update-grub='sudo grub2-mkconfig -o /boot/grub2/grub.cfg'" >> "$ALIASES"
      
  - name: Installing packages
    check_mode: on
    ansible.builtin.apt:
      name: "{{ pkgs_to_install }}"
      #name: "{{ item }}"
      state: present
    #loop: "{{ pkgs_to_install }}"
    
  # NOTE: Place code for installing RStudio here (if needed)
      
  - name: Installing Quentier
    check_mode: on
    ansible.builtin.command:
      cmd: konsole -e 'bash install_quentier.sh "debian bullseye" apt'
      
  - name: Starting Quentier sync with Evernote
    check_mode: on
    ansible.builtin.command:
      cmd: konsole -e 'quentier &'
      
  - name: Configuring VMM (Virtual Machine Manager)
    check_mode: on
    ansible.builtin.command:
      cmd: konsole -e 'bash install_VMM.sh "debian bullseye" apt'
      
  # TODO: Make list for aliases (currently, the only ones added are from visudo_edits.sh)
  #- name: 
      
# Play for user program configuations
- name: Configuring user programs
  hosts: localhost
  connection: local
  vars_files:
    - nano_config_options.yml
  
  tasks:
  - name: Reassign Okular shortcut for full screen mode from Ctrl+Shift+F to F11
    ansible.builtin.replace:
      path: ~/.local/share/kxmlgui5/okular/shell.rc
      regexp: '</gui>' # NOTE: This might need to be </kpartgui>
      replace: '  <Action shortcut="F11" name="fullscreen"/>\n </ActionProperties>\n</gui>'
      
  - name: Configuring Nano
    include_tasks: nano_config.yml
      
  # NOTE: This might need to be it's own playbook included here somehow
  - name: Configuring SSH
    ansible.builtin.command:
      cmd: konsole -e 'bash ssh_config.sh'
    
# Play for configuring Git
- name: Configuring Git
  hosts: localhost
  connection: local
  
  tasks:
  - name: Installing Git
    become: yes
    ansible.builtin.apt:
      name: git
      state: latest
      
  - name: Setting Username
    ansible.builtin.command:
      cmd: git config --global user.name "TheOGChips"
      
  - name: Setting E-mail
    ansible.builtin.command:
      cmd: git config --global user.email "swindell.christian.g@gmail.com"
      
  - name: Setting Credential Helper
    ansible.builtin.command:
      cmd: git config --global credential.helper store
      
  - name: Setting SSH key
    ansible.builtin.command:
      cmd: git config --global core.sshCommand "ssh -i ~/.ssh/github -F /dev/null"
      
# Play for debugging stuff
- name: Debugging stuff
  hosts: localhost
  connection: local
  become_user: chris
  
  tasks:
  - name: 'DEBUGGING: Removing aliases file'
    check_mode: off
    ansible.builtin.file:
      name: $HOME/.aliases
      state: absent
      
  - name: 'DEBUGGING: Removing $HOME/.nanorc'
    check_mode: off
    ansible.builtin.file:
      name: $HOME/.nanorc
      state: absent
