# run using ansible-playbook -K init.yml
---
# The general play
# echo "alias su='sudo su'" >> "$HOME"/.aliases

- name: Complete initial setup of localhost
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - install_packages.yml
  #become_method: sudo
  #vars_files:
  #- vars/main.yml

  #roles:
  #- role: geerlingguy.apache

  tasks:
  - name: Remove unwanted KDE packages
    check_mode: on
    ansible.builtin.apt:
      name: "{{ pkgs_to_remove + pkgs_to_remove_from_debian }}"
      state: absent
      
  - name: Remove these packages manually
    block:
      - name: Attempting to remove packages
        ansible.builtin.shell:
          cmd: rm -r $(find / -name "{{ item }}")
          warn: false
        loop:
          - '*contactthemeeditor*'
          - '*contactprintthemeeditor*'
          - '*headerthemeeditor*'
          - '*pimdataexporter*'
          - '*sieveeditor*'
    rescue:
      - name: Files couldn't be found
        ansible.builtin.debug:
          msg: The files could not be found and have likely already been deleted'
      
      #ignore_errors: true
    #ansible.builtin.copy:
      #src: files/site/index.html
      #dest: /var/www/html/index.html
      #owner: root
      #group: root
      #mode: 0644
  - name: Upgrade current packages on machine
    ansible.builtin.apt:
      upgrade: safe
      
  - name: Install net-tools
    ansible.builtin.apt:
      name: net-tools
      state: latest
      
  - name: Make edits to /etc/sudoers
    become_user: chris
    ansible.builtin.command:
      cmd: konsole -e 'bash visudo_edits.sh apt dpkg $HOME/.aliases'
      
  - name: Removing GRUB menu timeout
    ansible.builtin.replace:
      path: /etc/default/grub
      regexp: 'GRUB_TIMEOUT=5'
      replace: 'GRUB_TIMEOUT=-1'
      
  - name: Updating GRUB
    ansible.builtin.command:
      cmd: update-grub
    # echo "alias update-grub='sudo grub2-mkconfig -o /boot/grub2/grub.cfg'" >> "$ALIASES"
      
  - name: Installing packages
    check_mode: on
    ansible.builtin.apt:
      #name: "{{ pkgs_to_install }}"
      name: "{{ item }}"
      state: present
    loop: "{{ pkgs_to_install }}"
      
      
  #- name: Installing packages p2
    #ansible.builtin.apt:
      #name: gprolog{,-doc},htop,julia{,-doc},kate,k{mahjongg,nights,pat,sudoku}
      #state: present
      
  #- name: Installing packages p3
    #ansible.builtin.apt:
      #name: libreoffice-{writer,calc,impress},make,nasm,neofetch,plank,ruby,plasma-browser-integration
      #state: present
      
  #- name: Installing packages p4
    #ansible.builtin.apt:
      #name: python3-pip,racket{,-doc},screen,simplescreenrecorder,sl,texstudio,thefuck,thunderbird,tree
      #state: present
      
  #- name: Installing packages p5
    #ansible.builtin.apt:
      #name: vinagre,vlc,zsh
      #state: present
      
# Play for user program configuations
- name: Configuring user programs
  hosts: localhost
  connection: local
  
  tasks:
  - name: Reassign Okular shortcut for full screen mode from Ctrl+Shift+F to F11
    ansible.builtin.replace:
      path: ~/.local/share/kxmlgui5/okular/shell.rc
      regexp: '</gui>' # NOTE: This might need to be </kpartgui>
      replace: '  <Action shortcut="F11" name="fullscreen"/>\n </ActionProperties>\n</gui>'
      
  - name: Configuring Nano
    ansible.builtin.command:
      cmd: bash nano_config.sh
      
  - name: Configuring SSH
    ansible.builtin.command:
      cmd: konsole -e 'bash ssh_config.sh'
    
# Play for configuring Git
- name: Configuring Git
  hosts: localhost
  connection: local
  
  tasks:
  - name: Installing Git
    become: yes
    ansible.builtin.apt:
      name: git
      state: latest
      
  - name: Setting Username
    ansible.builtin.command:
      cmd: git config --global user.name "TheOGChips"
      
  - name: Setting E-mail
    ansible.builtin.command:
      cmd: git config --global user.email "swindell.christian.g@gmail.com"
      
  - name: Setting Credential Helper
    ansible.builtin.command:
      cmd: git config --global credential.helper store
      
  - name: Setting SSH key
    ansible.builtin.command:
      cmd: git config --global core.sshCommand "ssh -i ~/.ssh/github -F /dev/null"
      
# Play for debugging stuff
- name: Debugging stuff
  hosts: localhost
  connection: local
  #become_user: chris
  
  tasks:
  - name: 'DEBUGGING: Removing aliases file'
    #become_user: chris
    ansible.builtin.file:
      name: /home/chris/.aliases
      state: absent
