# NOTE: Only necessary for Red Hat-based distros
---
- name: Creating link to /run/media
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - debug_mode.yml
    
  tasks:
    - name: 'MEDIA: Removing /media'
      check_mode: '{{ debug_mode }}'
      ansible.builtin.file:
        path: /media
        state: absent
        
    - name: 'MEDIA: Creating link to /run/media'
      check_mode: '{{ debug_mode }}'
      ansible.builtin.file:
        #path: /media
        path: /temp
        src: /run/media
        state: link
