---
- name: Setting up local app environment
  hosts: localhost
  connection: local
  vars:
    - LOCAL: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local"
    - local_dirs:
      - bin
      - include
      - src
    - local_share_dirs:
      - share/gnote
      - share/vinagre
  vars_files:
    - debug_mode.yml
  
  tasks:
  - name: Copying directories into {{ LOCAL }}
    check_mode: '{{ debug_mode }}'
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: '{{ LOCAL }}'
    loop: '{{ local_dirs }}'
  
  - name: Copying directories into {{ LOCAL }}/share
    check_mode: '{{ debug_mode }}'
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: '{{ LOCAL }}/share'
    loop: '{{ local_share_dirs }}'
