---
# NOTE: In case these problems come up in the future
### opam configuration (alternatively, ~/.bashrc can be chosen when running opam init if ~/.profile is giving issues)
###test -r /home/chris/.opam/opam-init/init.sh && . /home/chris/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

###I had to use this one time because a switch wasn't created when I ran opam init (haven't had that problem before or since, though)
###opam switch create ocaml-base-compiler

- name: OCaml installation
  hosts: localhost
  connection: local
  vars_files:
    - debug_mode.yml
    - pkgs_to_install.yml
    
  - name: Initializing OPAM
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      cmd: opam init
    
  - name: Starting OPAM environment
    check_mode: '{{ debug_mode }}'
    ansible.builtin.shell:
      cmd: eval $(opam env --switch=default)
  
  - name: Installing OPAM packages
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      cmd: opam install {{ item }}
    loop: '{{ pkgs_to_install_from_opam + pkgs_to_install_from_opam_for_redhat_distros }}'
  
  - name: Running OPAM user setup
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      cmd: opam user-setup install
    
  - name: Finalizing OPAM environment
    check_mode: '{{ debug_mode }}'
    ansible.builtin.shell:
      cmd: eval $(opam env)
  
# NOTE: ocaml-top needs to be run from the command line (i.e. "$ ocaml-top")
