---
- name: Configuring SSH
  hosts: localhost
  connection: local
  vars:
    - ssh: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
    - ssh_config: "{{ ssh }}/config"
    - key_names:
      - "github"
      - "gitlab"
      #- "physics-lab"
      - "razzpi"
  vars_files:
    - debug_mode.yml
  
  tasks:
  - name: Attempting to generate SSH keys
    block:
      - name: Generating SSH keys
        check_mode: '{{ debug_mode }}'
        ansible.builtin.command:
          cmd: ssh-keygen -b 4096 -t ed25519 -f {{ ssh }}/{{ item }}
        loop: '{{ key_names }}'
    rescue:
      - name: Error generating SSH keys
        ansible.builtin.debug:
          msg: SSH keys likely already exist. Check the error message.
  
  - name: Copying SSH config file to {{ ssh }}
    block:
      - name: Attempting to copy SSH config file to {{ ssh }}
        check_mode: '{{ debug_mode }}'
        ansible.builtin.copy:
          src: ssh_config.txt
          dest: '{{ ssh_config }}'
    rescue:
      - name: SSH config file not found
        ansible.builtin.debug:
          msg: SSH config file not found and could not be copied. You'll have to create it manually.
    
  #- name: Copying SSH key to {{ key_names[2] }}
  #  check_mode: '{{ debug_mode }}'
  #  ansible.builtin.command:
  #    cmd: ssh-copy-id -i {{ ssh }}/{{ key_names[2] }} cswindell@{{ key_names[2] }}
