---
- name: VMware Horizon
  hosts: localhost
  connection: local
  vars_files:
    - debug_mode.yml
  vars:
    - bundle: vmware_horizon_client_x64.bundle
    - version: 2206-8.6.0-20094634
    - bundle_path: "{{ lookup('ansible.builtin.env', 'HOME') }}/Downloads/{{ bundle }}"

  tasks:
    - name: 'VMware HORIZON: Downloading bundle'
      check_mode: '{{ debug_mode }}'
      ansible.builtin.get_url:
        url: https://download3.vmware.com/software/CART23FQ2_LIN64_2206/VMware-Horizon-Client-{{ version }}.x64.bundle
        dest: '{{ bundle_path }}'
        mode: a+x
        
    - name: 'VMware HORIZON: Installing VMware Horizon'
      check_mode: '{{ debug_mode }}'
      ansible.builtin.shell:
        cmd: konsole -e 'sudo {{ bundle_path }}'
        
    - name: 'VMware HORIZON: Removing bundle'
      check_mode: '{{ debug_mode }}'
      ansible.builtin.file:
        path: '{{ bundle_path }}'
        state: absent
