---
- name: Z Shell configuration
  hosts: localhost
  connection: local
  vars_files:
    - debug_mode.yml
  
  tasks: 
  - name: 'ZSH: Copying user Z shell config files'
    check_mode: '{{ debug_mode }}'
    ansible.builtin.copy:
      src: zsh/{{ lookup('ansible.builtin.env', 'USER') }}.{{ item }}
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.{{ item }}"
      owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
      group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    loop:
      - zshrc
      - zprofile
      - zshenv
      - zkbd
      
  - name: 'ZSH: Copying root Z shell config files'
    check_mode: '{{ debug_mode }}'
    become: yes
    ansible.builtin.copy:
      src: zsh/root.{{ item }}
      dest: /root/.{{ item }}
      owner: root
      group: root
    loop:
      - zshrc
      - zprofile
      - zshenv
      - zkbd
      
  - name: 'ZSH: Changing default shell to Z shell'
    check_mode: '{{ debug_mode }}'
    ansible.builtin.command:
      cmd: konsole -e 'chsh -s /usr/bin/zsh'
